config/routes.rb
EquipmentDb::Application.routes.draw do
  root :to => 'home#show'

  resources :categories, :only => [:create, :destroy, :index, :new]

  resources :devices, :only => [:create, :destroy, :edit, :new, :show, :update] do
    resources :maintainers, :only => [:create, :destroy, :new]
    resources :owners, :only => [:create, :destroy, :new]
    resources :tickets, :only => [:create, :new, :update]
  end

  resources :owners, :only => [:create, :destroy, :index, :new]

  resources :reports, :only => [:show]

  resources :users, :only => [:index, :update]
  devise_for :users

  resources :wiki_pages, :only => [:show]
end

app/models/page_models/home/show.rb
module PageModels
  module Home
    class Show
      def initialize(categories, uncategorised_devices)
        @categories = categories
        @uncategorised_devices = uncategorised_devices
      end

      def sections
        return @sections if @sections
        @sections = @categories.map do |category|
          {:name => category.name, :devices => category.devices.find(:all, :order => 'name').map{|device| DeviceRow.new(device)}}
        end
        @sections << {:name => '(No Category)', :devices => @uncategorised_devices.map{|device| DeviceRow.new(device)}}
        @sections
      end
    end
  end
end

app/models/page_models/home/show/device_row.rb
module PageModels
  module Home
    class Show
      class DeviceRow
        def initialize(device)
          @device = device
        end

        def asset_code
          @device.asset_code.blank? ? '(untagged)' : @device.asset_code
        end

	def emphasize_status
          if @device.status && (@device.status.severity > Status::Severity::WARNING)
            true
          else
            false
          end
	end

	def highlight_style
          # Explicit: if no status recorded, return 'nil'
          return nil unless @device.status

          case @device.status.severity
          when Status::Severity::ERROR
            'error'
          when Status::Severity::WARNING
            'warning'
          end
	end

        def model
          @device.model
        end

	def name
	  @device.name
	end

	def path
          "/devices/#{@device.id}"
	end

	def status
          @device.status ? @device.status.name : '(not set)'
	end

        def training_category
          return '(not set)' unless @device.training_category
          case @device.training_category.name
          when 'Green'
            "<i class=\"icon-ok-circle\" style=\"background-color:\##{training_category_rgb}\"></i> Green</td>"
          when 'Yellow'
            "<i class=\"icon-warning-sign\" style=\"background-color:\##{training_category_rgb}\"></i> Yellow</td>"
          when 'Red'
            "<i class=\"icon-warning-sign\" style=\"background-color:\##{training_category_rgb}\"></i> Red</td>"
          end
        end

        def training_category_rgb
          @device.training_category ? @device.training_category.rgb : 'ffffff'
        end

        def wiki_url
          @device.reference_url
        end
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    categories = Category.find(:all, :order => 'name')
    uncategorised_devices = Device.find(:all, :conditions => 'category_id is null or category_id = -1', :order => 'name')
    @page = PageModels::Home::Show.new(categories, uncategorised_devices)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_device_row.html.erb
<tr<%=raw " class=\"#{device_row.highlight_style}\"" if device_row.highlight_style %>>
  <td><a href="<%=device_row.path %>"><%=device_row.name %></a></td>
  <td><%=device_row.model %></td>
  <td><%=device_row.asset_code %></td>
  <td>
    <% if device_row.emphasize_status %>
      <strong><%=device_row.status %></strong>
    <% else %>
      <%=device_row.status %>
    <% end %>
  </td>
  <td>
    <%= raw device_row.training_category %>
  </td>
  <td>
    <%= raw " <a href=\"#{device_row.wiki_url}\">wiki</a>" if !device_row.wiki_url.blank? %>
  </td>
</tr>

app/views/home/show.html.erb
<h1>All Makespace Equipment</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Make / Model</th>
      <th>Asset Code</th>
      <th>Status</th>
      <th><a href="http://makespace.org/wiki/index.php/Equipment/ToolClasses" target="_blank">Training Category</a></th>
      <th>Wiki Link</th>
    </tr>
  </thead>
  <tbody>
    <% @page.sections.each do |section| %>
      <% if section[:devices].size > 0 %>
        <tr>
          <td colspan="6"><em><%= section[:name] %></em></td>
        </tr>
        <% section[:devices].each do |device_row| %>
          <%= render :partial => 'device_row', :object => device_row %>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

<p><%= link_to "Add a device", new_device_path, class: 'btn btn-mini' %></p>

<h4>About this site</h4>
<p>The source code for this site lives at <a href="https://github.com/Makespace/equipment-db">https://github.com/Makespace/equipment-db</a>. Please report bugs and make feature requests using the GitHub ‘issues’ system.</p>