config/routes.rb
EquipmentDb::Application.routes.draw do
  root :to => 'home#show'

  resources :categories, :only => [:create, :destroy, :index, :new]

  resources :devices, :only => [:create, :destroy, :edit, :new, :show, :update] do
    resources :maintainers, :only => [:create, :destroy, :new]
    resources :owners, :only => [:create, :destroy, :new]
    resources :tickets, :only => [:create, :new, :update]
  end

  resources :owners, :only => [:create, :destroy, :index, :new]

  resources :reports, :only => [:show]

  resources :users, :only => [:index, :update]
  devise_for :users

  resources :wiki_pages, :only => [:show]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def require_authorized_user
    render :template => 'sessions/unauthorized', :status => 401 unless current_user.authorized?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/forbidden.html.erb
<div class="hero-unit">
  <h1>Hello there!</h1>

  <br>

  <p>The <a href="http://makespace.org/">Makespace</a> equipment database lets
  you keep track of what equipment is in the space, whether it works and who is
  responsible for fixing it. Before you can start, however, you need to
  <%= link_to "sign in", new_session_path %> or
  <%= link_to "create an account", new_user_registration_path %>.</p>

  <p class="pull-right">
  <%= link_to "Create account", new_user_registration_path, class: 'btn btn-large' %>
  <%= link_to "Sign in »", new_session_path, class: 'btn btn-primary btn-large' %>
  </p>
</div>